Better idle conn handling when max open is unlimited
importcjj/mobc pull request #85
Opened 2023-09-27 22:15 UTC by dcormier

* Treat `max_idle == 0` as unlimited idle connections. In this case, open connections will be limited by `max_open`.
* Allow Builder to be configured with `max_idle > max_open` when `max_open == 0`, matching the behavior of `Pool::set_max_idle_conns()`

Fixes #81

2023-09-28 12:46 UTC, garrensmith commented
@dcormier awesome. Give me a few days to take a look and review

2023-09-29 08:10 UTC, garrensmith requested changes
Wow this is an awesome PR. Great tests and really nicely thought out. I have a few very small changes I need you to do and then this is ready to go. Thanks for working on this.

2023-09-29 13:12 UTC, dcormier commented on src/lib.rs
> +#[derive(Debug, Clone, Copy)]
It was useful with an earlier iteration of the tests. I'll remove it.

2023-09-29 13:13 UTC, dcormier commented on src/lib.rs
>                  conn.close(&self.0.state);
Thanks. Good catch.

2023-09-29 13:22 UTC, dcormier commented on src/config.rs
> +        };
Would you like the `Pool::set_max_idle_conns()` logic to be changed in the same way? Currently it's:

```rust
        internals.config.max_idle =
            if internals.config.max_open > 0 && n > internals.config.max_open {
                internals.config.max_open
            } else {
                n
            };
```

Changing it to be similar would be:

```rust 
        internals.config.max_idle = n;
        if internals.config.max_open > 0 && internals.config.max_idle > internals.config.max_open {
            internals.config.max_idle = internals.config.max_open;
        }
```

Alternatively:

```rust
        if internals.config.max_open > 0 && n > internals.config.max_open {
            n = internals.config.max_open;
        }
        internals.config.max_idle = n;
```

2023-09-29 13:29 UTC, dcormier commented
> Wow this is an awesome PR. Great tests and really nicely thought out.

Thank you very much!

> I have a few very small changes I need you to do and then this is ready to go.

All changed.

> Thanks for working on this.

You're very welcome. Thank you for your work on this crate. It's nice to use.

2023-10-02 11:26 UTC, garrensmith commented on src/config.rs
> +        };
let's leave it for now.

2023-10-02 11:28 UTC, garrensmith approved these changes
Thank you. This is great.

2023-10-02 11:28 UTC, merged

2023-10-19 08:19 UTC, garrensmith commented
Latest release is out with this fix https://github.com/importcjj/mobc/releases/tag/0.8.3